baseURL = "https://gracious-johnson-52ba87.netlify.app/"
disableLanguages = ["En"]
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Nanozistsanaat"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "صفحه‌ی اصلی"
languageCode = "fr-fr"
languageName = "Fr"
weight = 1
[[menu.footer]]
URL = "production"
name = "production"
[[menu.main]]
URL = "about"
name = "About"
weight = 4
[[menu.main]]
URL = "director"
name = "directors"
weight = 3
[[menu.main]]
URL = "production"
name = "production"
weight = 2
[[menu.main]]
URL = "contact"
name = "contact"
weight = 4
[params]
address = "دانشگاه صنعتی اصفهان"
author = "Themefisher"
contact_form_action = "#"
description = "شرکت نانوزیست صنعت اهورا (سهامی خاص) در سال 1397 به همت جمعی از اساتید متخصص و فناور دانشگاه صنعتی اصفهان تاسیس شد. هدف از تاسیس این شرکت فعالیت در عرصه‏ اقتصاد دانش ‏بنیان با تجاری سازی و تولید انبوه محصولات بر پایه‏ ی دانش فنی کارشناسان و پژوهشگران متخصص است. امید است که با تلاش و پیگیری کارشناسان و مدیران متخصص و متعهد شرکت، گامی در شکوفایی و پیشرفت اقتصاد دانش ‏بنیان این مرز و بوم برداشته شود."
email = "nanozistsanaat@gmail.com"
google_analitycs_id = ""
logo = "/images/photo_2020-12-04_14-18-58-removebg-preview.png"
mobile = "+983133912282"
top_header = false
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBMLkTt4KvW6vYa1-6Dn6hwDkMpRYPjff8"
map_latitude = "32.719038"
map_longitude = "51.531987"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
